#!/usr/bin/env python3
"""
School Dashboard Email Fetcher
================================
E153.manager@gmail.com is a dedicated dashboard inbox.
All emails are forwarded here by Suruchi (suruchi.garg@gmail.com)
or Akshat (thisisakshat@gmail.com) from their school email accounts.

Claude reads each email and decides:
  - Is it for Arjun (Shiv Nadar School, Grade 7)?
  - Is it for Myra (Kunskapsskolan, KG)?
  - Or is it irrelevant / spam?

Usage:
  python3 backend/fetch_emails.py              # today only
  python3 backend/fetch_emails.py --days 7     # backfill last N days
"""

import os
import re
import json
import imaplib
import email
import argparse
from datetime import date, timedelta, datetime, timezone
from email.header import decode_header
from pathlib import Path

import io
import pdfplumber
from dotenv import load_dotenv
from google import genai

# ── Config ─────────────────────────────────────────────────
load_dotenv(Path(__file__).parent.parent / ".env", override=True)

GMAIL_USER         = "E153.manager@gmail.com"
GMAIL_APP_PASSWORD = os.environ["GMAIL_APP_PASSWORD"].replace(" ", "")

BASE_DIR        = Path(__file__).parent.parent
DATA_FILE       = BASE_DIR / "data" / "dashboard-data.js"
CONFIG_FILE     = BASE_DIR / "data" / "dashboard-config.js"
TIMETABLE_FILE  = BASE_DIR / "data" / "timetable.json"
GITHUB_TOKEN    = os.environ.get("GITHUB_TOKEN", "")
GITHUB_OWNER    = "suruchigarg10"
GITHUB_REPO     = "school-dashboard"

CORE_SUBJECTS = [
    "Math", "English", "Hindi", "Social Science",
    "Physics", "Chemistry", "Biology", "IT", "Spanish"
]

# ── Load / Save dashboard-data.js ───────────────────────────

def load_data() -> dict:
    text = DATA_FILE.read_text(encoding="utf-8")
    match = re.search(r'window\.DASHBOARD_DATA\s*=\s*(\{.*\})\s*;', text, re.DOTALL)
    if not match:
        raise ValueError("Could not parse dashboard-data.js — JS wrapper not found")
    return json.loads(match.group(1))


def save_config():
    """Write dashboard-config.js with the GitHub token — gitignored, generated locally."""
    js = (
        "// Auto-generated by fetch_emails.py — do not edit or commit\n"
        "window.DASHBOARD_CONFIG = {\n"
        f'  githubOwner: "{GITHUB_OWNER}",\n'
        f'  githubRepo:  "{GITHUB_REPO}",\n'
        f'  githubToken: "{GITHUB_TOKEN}",\n'
        "};\n"
    )
    CONFIG_FILE.write_text(js, encoding="utf-8")
    print("✅  Saved data/dashboard-config.js")


def save_data(data: dict):
    now_iso = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%S.000Z")
    data["meta"]["lastUpdated"] = now_iso
    js = (
        "// ============================================================\n"
        "// dashboard-data.js — Auto-generated by the school dashboard\n"
        "// script. Do not edit manually.\n"
        f"// Last updated: {now_iso}\n"
        "// ============================================================\n\n"
        f"window.DASHBOARD_DATA = {json.dumps(data, indent=2, ensure_ascii=False)};\n"
    )
    DATA_FILE.write_text(js, encoding="utf-8")
    print("✅  Saved data/dashboard-data.js")


# ── Gmail IMAP ─────────────────────────────────────────────

def connect_gmail() -> imaplib.IMAP4_SSL:
    mail = imaplib.IMAP4_SSL("imap.gmail.com", 993)
    mail.login(GMAIL_USER, GMAIL_APP_PASSWORD)
    return mail


def decode_str(s) -> str:
    if not s:
        return ""
    parts = decode_header(s)
    result = []
    for part, enc in parts:
        if isinstance(part, bytes):
            result.append(part.decode(enc or "utf-8", errors="replace"))
        else:
            result.append(str(part))
    return "".join(result).strip()


def _clean_text(text: str) -> str:
    """Strip tracking URLs and excessive whitespace."""
    text = re.sub(r'<https?://\S+>', '', text)
    text = re.sub(r'https?://\S+', '', text)
    text = re.sub(r'\n{3,}', '\n\n', text)
    return text.strip()


def _extract_pdf_text(data: bytes) -> str:
    """Extract text from a PDF attachment. Returns '' on failure."""
    import warnings, logging
    logging.getLogger("pdfminer").setLevel(logging.ERROR)
    try:
        with warnings.catch_warnings():
            warnings.simplefilter("ignore")
            with pdfplumber.open(io.BytesIO(data)) as pdf:
                pages = [p.extract_text() or "" for p in pdf.pages[:6]]  # cap at 6 pages
                return _clean_text("\n\n".join(pages))[:3000]
    except Exception:
        return ""


def get_body_and_attachments(msg) -> tuple:
    """
    Returns (body: str, attachments: list[dict])
    Each attachment dict: { name, type, text }
      - text is populated for PDFs, empty for other types
    """
    body = ""
    attachments = []

    if msg.is_multipart():
        for part in msg.walk():
            disposition = str(part.get("Content-Disposition", ""))
            content_type = part.get_content_type()
            filename = part.get_filename()

            if filename:
                # It's an attachment
                raw_data = part.get_payload(decode=True) or b""
                att = {
                    "name": decode_str(filename),
                    "type": "pdf" if filename.lower().endswith(".pdf") else
                            "image" if content_type.startswith("image/") else "other",
                    "text": ""
                }
                if att["type"] == "pdf":
                    att["text"] = _extract_pdf_text(raw_data)
                attachments.append(att)

            elif content_type == "text/plain" and "attachment" not in disposition and not body:
                charset = part.get_content_charset() or "utf-8"
                body = part.get_payload(decode=True).decode(charset, errors="replace")
    else:
        charset = msg.get_content_charset() or "utf-8"
        payload = msg.get_payload(decode=True)
        if payload:
            body = payload.decode(charset, errors="replace")

    body = _clean_text(body)[:4000]
    return body, attachments


def fetch_all_emails_for_date(mail: imaplib.IMAP4_SSL, target_date: date) -> list[dict]:
    """Fetch every email in the inbox received on target_date."""
    mail.select("INBOX")
    imap_since  = target_date.strftime("%d-%b-%Y")
    imap_before = (target_date + timedelta(days=1)).strftime("%d-%b-%Y")

    _, msg_ids = mail.search(None, f'(SINCE {imap_since} BEFORE {imap_before})')
    ids = msg_ids[0].split()
    print(f"   {len(ids)} email(s) found on {target_date}")

    emails = []
    for uid in ids:
        _, msg_data = mail.fetch(uid, "(RFC822)")
        raw = msg_data[0][1]
        msg = email.message_from_bytes(raw)
        body, attachments = get_body_and_attachments(msg)
        emails.append({
            "subject":     decode_str(msg.get("Subject", "")),
            "from":        decode_str(msg.get("From", "")),
            "body":        body,
            "attachments": attachments,
        })
    return emails


# ── Claude ─────────────────────────────────────────────────

def _get_client():
    return genai.Client(api_key=os.environ["GEMINI_API_KEY"].strip())


def _parse_json(text: str) -> dict:
    try:
        return json.loads(text)
    except json.JSONDecodeError:
        match = re.search(r'\{.*\}', text, re.DOTALL)
        if match:
            try:
                return json.loads(match.group())
            except json.JSONDecodeError:
                pass
    return {}


def classify_and_summarise(raw: dict, target_date: date, core_today: list[str]):
    """
    Single Claude call that:
      1. Decides if the email is for Arjun, Myra, or neither
      2. Produces a clean summary and structured fields

    Returns a dict with a top-level "kid" key ("arjun" | "myra" | "skip"),
    or None if the email should be ignored.
    """
    day_name = target_date.strftime("%A")
    date_str = target_date.isoformat()

    # Build attachment context
    att_names = [a["name"] for a in raw.get("attachments", [])]
    att_context = ""
    if att_names:
        att_context = f"\nAttachments: {', '.join(att_names)}"
        pdf_texts = [a["text"] for a in raw.get("attachments", []) if a.get("text")]
        if pdf_texts:
            att_context += "\n\nAttachment content:\n" + "\n---\n".join(pdf_texts)

    prompt = f"""You are processing emails forwarded to a dedicated school-dashboard inbox.
Emails are forwarded by parents (suruchi.garg@gmail.com or thisisakshat@gmail.com).

Two children:
  • Arjun Kumar — Grade 7, Shiv Nadar School, Gurugram
    Core subjects: {', '.join(CORE_SUBJECTS)}
    Today ({day_name} {date_str}) subjects: {', '.join(core_today) if core_today else 'unknown'}
  • Myra Garg — Kindergarten (K2), Kunskapsskolan, Gurugram

Email:
From: {raw['from']}
Subject: {raw['subject']}
Body:
{raw['body']}{att_context}

Step 1 — Which child is this about?
  - Mentions "Shiv Nadar", "Grade 7", "Arjun", or core subjects → "arjun"
  - Mentions "Kunskapsskolan", "Kunskappskolan", "K2", "Myra", kindergarten → "myra"
  - Cannot clearly tell → "skip"
Do NOT guess. Only assign arjun/myra if the content makes it clear.

Step 2 — Fill the right JSON schema. Reply with ONLY valid JSON, no markdown fences.

CRITICAL RULE: Never invent data. If something is not clearly stated in the email, leave the field empty.

If kid="arjun":
{{
  "kid": "arjun",
  "summary": "2-3 sentence plain-English summary. No URLs.",
  "tags": [],
  "schoolSubject": null,
  "todoItems": [],
  "homeworkItems": [],
  "veracrossItems": [],
  "topicsCovered": [],
  "examSchedule": [],
  "holidays": []
}}
  tags: any of ["announcement","hw","test","chapter","veracross"]
  schoolSubject: one of the core subjects, or null
  todoItems: EVERY action item from email + attachments.
    Format: [{{"id":"","text":"Fill Club Section form","owner":"Arjun","dueDate":"YYYY-MM-DD","source":"Club circular"}}]
    Include: forms to submit, things to bring, payments, Veracross downloads, homework, test prep.
    owner: "Arjun" if Arjun must do it himself (homework, bring something, study), "Parent" if parent must act (pay fee, fill form, register online, download from portal).
    Leave "id" as empty string "".
  homeworkItems: [{{"subject":"Math","description":"...","dueDate":"YYYY-MM-DD"}}] or []
  veracrossItems: [{{"action":"...","detail":"...","done":false}}] only for Veracross portal actions
  topicsCovered: Teacher/subject emails only. [{{"subject":"Math","topic":"Chapter + concept, be specific e.g. 'Ch 4: Rational Numbers - comparing fractions'"}}] Up to 4 DISTINCT topics/chapters — each entry must cover a genuinely different concept, not the same thing rephrased. If two extracted topics are about the same chapter/concept, merge them into one. [] for admin/fee/event emails.
  examSchedule: Only actual exam dates for Grade 7 Arjun. Do NOT include senior grade exams (Grade 10/11/12, IBDP, CBSE Board). [{{"examType":"UT1|UT2|MidTerm|FinalTerm|ClassTest|Other","subject":"Math","examDate":"YYYY-MM-DD","topics":"..."}}] else [].
  holidays: Only if school closure/holiday dates mentioned. [{{"date":"YYYY-MM-DD","name":"Diwali Break","type":"holiday"}}] else [].

If kid="myra":
{{
  "kid": "myra",
  "summary": "2-3 sentence plain-English summary. No URLs.",
  "tags": [],
  "todoItems": [],
  "category": "general"
}}
  tags: any of ["announcement","hw","event","transport","fee"]
  todoItems: EVERY action item for parents from email + attachments.
    Format: [{{"id":"","text":"Pay Q1 fee before April 15","owner":"Parent","dueDate":"YYYY-MM-DD","source":"Fee invoice"}}]
    owner: always "Parent" for Myra since she is in KG.
    Leave "id" as empty string "".
  category: one of ["general","homework","event","transport","fee","announcement"]

If kid="skip":
{{"kid":"skip"}}"""

    resp = _get_client().models.generate_content(
        model="gemini-2.5-flash",
        contents=prompt,
    )
    result = _parse_json(resp.text)
    kid = result.get("kid", "skip")

    if kid == "skip" or not kid:
        print(f"    ⏭️  Skipped (not school-related): {raw['subject'][:60]}")
        return None

    if kid == "arjun":
        todos = _stamp_todo_ids(result.get("todoItems", []), date_str, "arjun")
        return {
            "kid":              "arjun",
            "subject":          raw["subject"],
            "from":             raw["from"],
            "summary":          result.get("summary", ""),
            "tags":             result.get("tags", []),
            "schoolSubject":    result.get("schoolSubject"),
            "attachments":      [{"name": a["name"], "type": a["type"]} for a in raw.get("attachments", [])],
            "todoItems":        todos,
            "_homeworkItems":   result.get("homeworkItems", []),
            "_veracrossItems":  result.get("veracrossItems", []),
            "_topicsCovered":   result.get("topicsCovered", []),
            "_examSchedule":    result.get("examSchedule", []),
            "_holidays":        result.get("holidays", []),
        }

    if kid == "myra":
        todos = _stamp_todo_ids(result.get("todoItems", []), date_str, "myra")
        return {
            "kid":         "myra",
            "subject":     raw["subject"],
            "from":        raw["from"],
            "summary":     result.get("summary", ""),
            "tags":        result.get("tags", []),
            "attachments": [{"name": a["name"], "type": a["type"]} for a in raw.get("attachments", [])],
            "todoItems":   todos,
            "category":    result.get("category", "general"),
        }

    return None


def _stamp_todo_ids(todos: list, date_str: str, kid: str) -> list:
    """Assign stable IDs to todo items based on content hash."""
    import hashlib
    result = []
    for t in todos:
        text = t.get("text", "")
        raw_id = f"{kid}-{date_str}-{text}"
        stable_id = kid[0] + "-" + hashlib.md5(raw_id.encode()).hexdigest()[:10]
        result.append({**t, "id": stable_id, "done": False})
    return result


def build_arjun_day_summary(processed: list[dict], subjects: list[str], target_date: date) -> str:
    day_name = target_date.strftime("%A")
    date_str = target_date.isoformat()
    if not processed:
        return (
            f"No school emails received today ({day_name}, {date_str}).\n\n"
            f"Today's subjects: {', '.join(subjects)}."
        )
    bullets = "\n".join(f"- {e['subject']}: {e['summary']}" for e in processed)
    resp = _get_client().models.generate_content(
        model="gemini-2.5-flash",
        contents=(
            f"Write a 3-4 sentence daily briefing for parents about their Grade 7 child's school day.\n"
            f"Today is {day_name}, {date_str}. Subjects: {', '.join(subjects)}.\n\n"
            f"Email summaries:\n{bullets}\n\n"
            "Plain, warm, flowing sentences. No bullet points."
        ),
    )
    return resp.text.strip()


def build_myra_day_summary(processed: list[dict], target_date: date) -> str:
    if not processed:
        return f"No school emails received ({target_date.strftime('%A')}, {target_date.isoformat()})."
    return "\n".join(f"• {e['subject']}: {e['summary']}" for e in processed)


# ── Process one day ─────────────────────────────────────────

def process_day(target_date: date, data: dict, timetable: dict, mail: imaplib.IMAP4_SSL):
    day_name = target_date.strftime("%A")
    date_str = target_date.isoformat()
    today_subjects = timetable.get("timetable", {}).get(day_name, [])
    core_today = [s for s in today_subjects if s in CORE_SUBJECTS]

    print(f"\n📅  {date_str} ({day_name})")
    raw_emails = fetch_all_emails_for_date(mail, target_date)

    arjun_processed, myra_processed = [], []
    all_hw, all_vc, all_topics, all_exams, all_holidays = [], [], [], [], []

    import time as _time
    for raw in raw_emails:
        print(f"   🔍 {raw['subject'][:70]}")
        result = classify_and_summarise(raw, target_date, core_today)
        _time.sleep(5)  # stay within Gemini free tier: 15 req/min
        if result is None:
            continue

        if result["kid"] == "arjun":
            all_hw.extend(result.pop("_homeworkItems", []))
            all_vc.extend(result.pop("_veracrossItems", []))
            # New: topics, exams, holidays
            for t in result.pop("_topicsCovered", []):
                t["date"]   = date_str
                t["source"] = result.get("subject", "")
                all_topics.append(t)
            for e in result.pop("_examSchedule", []):
                all_exams.append(e)
            for h in result.pop("_holidays", []):
                all_holidays.append(h)
            result.pop("kid")
            arjun_processed.append(result)
            print(f"       → Arjun ({'·'.join(result.get('tags', [])) or 'general'})")

        elif result["kid"] == "myra":
            result.pop("kid")
            myra_processed.append(result)
            print(f"       → Myra ({result.get('category', 'general')})")

    # ── Arjun's day entry ───────────────────────────────────
    arjun_summary = build_arjun_day_summary(arjun_processed, core_today, target_date)
    arjun_day = {
        "date":           date_str,
        "summary":        arjun_summary,
        "emails":         arjun_processed,
        "veracrossItems": all_vc,
        "topicsCovered":  [t["topic"] for t in all_topics],
        "homeworkItems":  all_hw,
    }
    idx = next((i for i, d in enumerate(data["days"]) if d["date"] == date_str), None)
    if idx is not None:
        data["days"][idx] = arjun_day
    else:
        data["days"].insert(0, arjun_day)

    # Veracross log
    if all_vc:
        vc_idx = next((i for i, v in enumerate(data["veracrossLog"]) if v["date"] == date_str), None)
        if vc_idx is not None:
            data["veracrossLog"][vc_idx]["items"] = all_vc
        else:
            data["veracrossLog"].insert(0, {"date": date_str, "items": all_vc})

    # Topic log — cumulative, deduplicate by subject+date+first-50-chars-of-topic
    topic_log = data.setdefault("topicLog", [])
    for t in all_topics:
        topic_prefix = t["topic"][:50].lower().strip()
        existing = next(
            (x for x in topic_log
             if x["subject"] == t["subject"]
             and x["date"] == date_str
             and x["topic"][:50].lower().strip() == topic_prefix),
            None
        )
        if not existing:
            topic_log.insert(0, t)
            print(f"       📚 Topic: [{t['subject']}] {t['topic'][:60]}")

    # Exam schedule — deduplicate by subject+date; skip non-Grade-7 exams
    GRADE7_SKIP_KEYWORDS = ["grade 11", "grade 12", "ibdp", "ib dp", "xi ", "xii ", " x ", " x\n",
                             "cbse board", "class 11", "class 12", "class x ", "class xi", "class xii"]
    exam_sched = data.setdefault("examSchedule", [])
    for e in all_exams:
        subj_lower   = e.get("subject", "").lower()
        topics_lower = e.get("topics", "").lower()
        # Skip if this exam is clearly for senior grades, not Grade 7
        if any(kw in subj_lower or kw in topics_lower for kw in GRADE7_SKIP_KEYWORDS):
            continue
        existing = next(
            (x for x in exam_sched if x["subject"] == e["subject"] and x["examDate"] == e["examDate"]),
            None
        )
        if not existing:
            exam_sched.insert(0, e)
            print(f"       📝 Exam: [{e.get('examType','')}] {e['subject']} on {e['examDate']}")

    # Holidays — deduplicate by date
    holiday_list = data.setdefault("holidays", [])
    for h in all_holidays:
        existing = next((x for x in holiday_list if x["date"] == h["date"]), None)
        if not existing:
            holiday_list.insert(0, h)
            print(f"       🎉 Holiday: {h['name']} on {h['date']}")

    # ── Myra's day entry ────────────────────────────────────
    myra_summary = build_myra_day_summary(myra_processed, target_date)
    myra_day = {
        "date":    date_str,
        "summary": myra_summary,
        "emails":  myra_processed,
    }
    myra_days = data.setdefault("myra", {}).setdefault("days", [])
    m_idx = next((i for i, d in enumerate(myra_days) if d["date"] == date_str), None)
    if m_idx is not None:
        myra_days[m_idx] = myra_day
    else:
        myra_days.insert(0, myra_day)


# ── Entry point ─────────────────────────────────────────────

def main():
    parser = argparse.ArgumentParser(description="Fetch school emails and update dashboard")
    parser.add_argument(
        "--days", type=int, default=1,
        help="How many past days to fetch (default: 1 = today only)"
    )
    args = parser.parse_args()

    print("🏫  School Dashboard Email Fetcher")
    print(f"    Inbox : {GMAIL_USER}")
    print(f"    Days  : {args.days}")

    data      = load_data()
    timetable = json.loads(TIMETABLE_FILE.read_text(encoding="utf-8"))

    print("\n📧  Connecting to Gmail IMAP...")
    mail = connect_gmail()
    print("    Connected ✓")

    for offset in range(args.days):
        target = date.today() - timedelta(days=offset)
        process_day(target, data, timetable, mail)

    mail.logout()

    data["days"].sort(key=lambda d: d["date"], reverse=True)
    data["myra"]["days"].sort(key=lambda d: d["date"], reverse=True)

    save_data(data)
    save_config()
    print("\n✅  Done!")


if __name__ == "__main__":
    main()
